backend-code/SMP/urls.py
from django.urls import path,include
from SMP import views

app_name = 'SMP'
urlpatterns = [
    path('', views.indexView, name='index'),
    path('<sig_name>/', views.detailsView, name='details'),
]

backend-code/recruitment/urls.py
from django.urls import path,include
from recruitment import views

app_name = 'recruitment'
urlpatterns = [

    path('<sig_name>/',views.roundInfo, name = 'recs')
]

backend-code/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# admin.autodiscover()
# admin.site.enable_nav_sidebar = False
# a

admin.site.site_header = "ISTE Website Admin Page"
admin.site.index_title = "Admin page"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account")),
    path("project/", include("project.urls", namespace="project")),
    path("event/", include("event.urls", namespace="event")),
    path("recs/", include("recruitment.urls", namespace="recruitment")),
    path("sig/", include("sig.urls", namespace="sig")),
    path("team/", include("team.urls", namespace="team")),
    path("smp/", include("SMP.urls", namespace="SMP")),
    path("ctf/", include("ctf.urls", namespace="CTF")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("squareoneleaderboard/",include("squareonelb.urls", namespace="squareonelb")),
    path('obscura/', include('obscura.urls', namespace='obscura')),
    path('cryptonite/', include('cryptonite.urls', namespace='cryptonite')),
    path('obsidian/', include('obsidian.urls', namespace="obsidian")),
    path('gallery/',include("gallery.urls",namespace="gallery")),
    path('clutchMysteryBox/',include("clutchMysteryBox.urls",namespace="clutchMysteryBox"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend-code/recruitment/models.py
from django.db import models
from sig.models import SIG

# Create your models here.
class Round(models.Model):
    name = models.CharField(
        default = "",
        max_length = 200
    )
    description = models.TextField()
    sig = models.ForeignKey(
        SIG,
        on_delete=models.CASCADE,
    )
    date_time = models.DateTimeField(
        auto_now=False,
        blank=True
    )
    isDone = models.BooleanField(
        default = False
    )

    def __str__(self):
        return self.name + " - " + self.sig.name + ' - '


class RegLink(models.Model):
    sig = models.ForeignKey(
        SIG,
        on_delete=models.CASCADE,
    )
    link = models.URLField(max_length=200, default="")
    descriptionSIG = models.TextField(default="SIG description")

    def __str__(self):
        return self.sig.name + " - " + self.link
    

backend-code/recruitment/views.py
from django.shortcuts import render
from sig.models import SIG

from recruitment.models import Round
from recruitment.models import RegLink
from rest_framework.response import Response
from rest_framework.decorators import api_view
from recruitment.serializers import RoundSerializer
from team.models import Core

# GET API for recs backend
@api_view(['GET'])
def roundInfo(request,sig_name):
    context = {}
    sig = SIG.objects.get(
        name=sig_name )
    objRegLink = RegLink.objects.get(sig=sig)
    context['registerLink'] = objRegLink.link
    context['descriptionSIG'] = objRegLink.descriptionSIG 
    roundData = Round.objects.filter(
        sig=sig,
    ).order_by('date_time')
    rounds = RoundSerializer(roundData, many=True).data
    context['rounds'] = rounds

    return Response(context)

backend-code/templates/recruitment/details.html
{% extends 'base.html' %}
{% load split %}

{% block styles %}
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/recruitment/details.css' %}" media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/recruitment/timeline.css' %}" media="screen,projection"/>
{% endblock %}

{% block content %}

<center>
    <h3>
        {{rounds.0.sig}} Recruitments
    </h3>
</center>

<br><br>
<div id="lineCont"> 
    <div id="line"></div>
</div>
<br><br><br>
<div class="center flow-text" id="timelinePhones"></div>
<br><br><br><br>

{% for round in rounds %}
<div class="card z-depth-4">
    <div class="roundec flow-text">
        <center><h4>
            {{round.name}}
        </h4>
        <!-- <h5><b>{{round.date_time}}</b><br> -->
        </h5> 
        <h5>{{round.description}}</h5></center>
    </div>
</div>
<br>
{% endfor %}

<p class="grey-text text-darken-2">
    <h4>Point(s) of contact:</h4>
    <ul>
        {% for member in POC %}
                <li><h5>{{member.user.first_name}} {{member.user.last_name}} : <a href="tel: {{member.user.phone_number }} ">{{member.user.phone_number}}</a></h5></li>
        {% endfor %}
    </ul>
</p>
<br>
<div class="center" id="RegisterButton">
    <a href="{{reg_url}}" class="btn waves-effect indigo darken-4 white-text z-depth-4" target="_blank">Register</a>
</div>
<br><br>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/recruitment/timeline.js'%}"></script>
    <script>
        var name = new Array({% for round in rounds %}"{{ round.name|escapejs }}"{% if not forloop.last %},{% endif %}{% endfor %});
        var isDone = new Array({% for round in rounds %}"{{ round.isDone|escapejs }}"{% if not forloop.last %},{% endif %}{% endfor %});
        var name_arr = new Array(name.split(","));
        makeCircles(name_arr[0], isDone);
    </script>
{% endblock scripts %}

backend-code/templates/recruitment/faq.html
{% extends 'base.html' %}
{% load split %}

{% block styles %}
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/recruitment/index.css' %}"  media="screen,projection"/>
{% endblock %}

{% block content %}

<h3> Recruitment FAQs</h3><br>
<div class="container">
    <ol class="inst-list flow-text">
        <li>
            <p class="black-text">
                <a class="ques">Can I apply for multiple SIGs?</a><br>
                Yes. You can apply for as many SIGs as you want to. Fill out the form for each SIG you want to apply for separately.
            </p>
        </li>
        <li>
            <p class="black-text">
                <a class="ques">How will I know if I am selected for the next round?</a><br>
                You will receive an email and a message on WhatsApp regarding your selection for each round.
            </p>
        </li>
        <li>
            <p class="black-text">
                <a class="ques">Where can I view the details of the recruitment process for a SIG?</a><br>
                You can select the SIG from <a href="{% url 'recruitment:index' %}"><b>here</b></a> to see the details of the recruitment process of that SIG. 
                Additionally, you can also click on the <a class="btn waves-effect indigo darken-4 white-text "><b>APPLY FOR RECRUITMENT</b></a> button on the SIG's page to view the same.
            </p>
        </li>
        <li>
            <p class="black-text">
                <a class="ques">Does ISTE recruit 3rd years?</a><br>
                Yes we do! We do consider exceptional 3rd year candidates as well. However, a majority of our intake will comprise of 2nd years.
            </p>
        </li>
        <li>
            <p class="black-text">
                <a class="ques">I have a query not listed here, who can I contact?</a><br>
                Feel free to contact anyone below if you have any other doubts:<br>
                Amodh Shenoy: <a href="tel:9110837927">9110837927</a><br>
                Aditya Rastogi: <a href="tel:9886517191">9886517191</a><br>
                Nikhil Varghese: <a href="tel:8921374523">8921374523</a>
            </p>
        </li>
    </ol>
</div>

<br><br>

{% endblock %}

backend-code/templates/recruitment/index.html
{% extends 'base.html' %}
{% load split %}

{% block styles %}
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/recruitment/index.css' %}"  media="screen,projection"/>
{% endblock %}

{% block content %}
<h3>Instructions</h3><br>

<div class="container">
    <ol class="inst-list flow-text">
        <li>
            <p class="black-text">
                Select the appropriate card to go to that SIG's page. Click on the <a class="btn waves-effect indigo darken-4 white-text "><b>APPLY FOR RECRUITMENT</b></a> 
                button on that page to view the details of that SIG's recruitment process. 
            </p>           
        </li>
        <li>
            <p class="black-text">
                Click on the <a class="btn waves-effect indigo darken-4 white-text "><b>Register</b></a> button at the bottom of that page to be redirected to the registration form. 
            </p>
        </li>
        <li>
            <p class="black-text">
                You can register <b>ONLY</b> through your nitk.edu email id.
            </p>
        </li>
        <li>
            <p class="black-text">
                The registration forms close on <b>16th August(Sunday), 9:00PM.</b>
            </p>
        </li>
            
        <li>
            <p class="black-text">
                You will be notified via email and WhatsApp about any recruitment round timing and required
                 information. Make sure you check these frequently.
            </p>
        </li>
            
        <li>
            <p class="black-text">
                We will be having video interviews on Microsoft Teams, the details of which will be sent to you after the online tests.
            </p>
        </li>
        <li>
            <p class="black-text">
                You can find out more about each SIG 
                and the projects they have planned for this year on the respective SIG's page.
            </p>
        </li>
        <li>
            <p class="black-text">
                If you have any issues, contact the POC for that SIG directly.
            </p>
        </li>
    </ol>
</div>

<br>
<div class="row">
    <h3>
        <span>
            Special Interest Groups (SIGs)
        </span>
    </h3>
    {% for sig_choice in sigs %}
    <div class="col s12 l3 sigcard">
        <a href="{% url 'sig:details' sig_choice.name %}">
            <div class="card z-depth-4">
                <div class="card-image waves-effect waves-block waves-light ">
                    <img class="activator" src="/media/{{sig_choice.avatar}}">
                </div>
                <div class="card-content activator indigo darken-3 waves-effect waves-block waves-light">
                        <span class="card-title activator white-text text-darken-4 center">
                            {{sig_choice.name}}
                        </span>               
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>

{% endblock %}