backend-code/SMP/urls.py
from django.urls import path,include
from SMP import views

app_name = 'SMP'
urlpatterns = [
    path('', views.indexView, name='index'),
    path('<sig_name>/', views.detailsView, name='details'),
]

backend-code/sig/urls.py
from django.urls import path,include
from sig import views

app_name = 'sig'
urlpatterns = [
    path('<sig_name>/', views.detailsView, name='details'),
]

backend-code/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# admin.autodiscover()
# admin.site.enable_nav_sidebar = False
# a

admin.site.site_header = "ISTE Website Admin Page"
admin.site.index_title = "Admin page"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account")),
    path("project/", include("project.urls", namespace="project")),
    path("event/", include("event.urls", namespace="event")),
    path("recs/", include("recruitment.urls", namespace="recruitment")),
    path("sig/", include("sig.urls", namespace="sig")),
    path("team/", include("team.urls", namespace="team")),
    path("smp/", include("SMP.urls", namespace="SMP")),
    path("ctf/", include("ctf.urls", namespace="CTF")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("squareoneleaderboard/",include("squareonelb.urls", namespace="squareonelb")),
    path('obscura/', include('obscura.urls', namespace='obscura')),
    path('cryptonite/', include('cryptonite.urls', namespace='cryptonite')),
    path('obsidian/', include('obsidian.urls', namespace="obsidian")),
    path('gallery/',include("gallery.urls",namespace="gallery")),
    path('clutchMysteryBox/',include("clutchMysteryBox.urls",namespace="clutchMysteryBox"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend-code/sig/models.py
from django.db import models
from website.settings import SIG_CHOICES
from website.helperFunctions import sig_avatar_upload_path, default_sig_poster_path

# Create your models here.
class SIG(models.Model):
    name = models.CharField(
        max_length=9, 
        choices=SIG_CHOICES
    )
    #Picture of the SIG
    avatar = models.ImageField(
        default=default_sig_poster_path,
        upload_to=sig_avatar_upload_path,
        blank=True
    )
    #Text on SIG card, home page
    summary = models.TextField(
        default='SIG Summary',
        blank=False,
        editable=True
    )
    #Text on SIG page
    description = models.TextField(
        blank=False,
        editable=True,
    )
    #Link to google form for recs application
    reg_url = models.URLField(
        blank=False,
        editable=True,
        default=''
    )
    #Link to the video on SIG page
    website_talk_url = models.URLField(
        blank=False,
        editable=True,
        default=''
    )
    def __str__(self):      
        return self.name

backend-code/sig/views.py
from django.shortcuts import render
from project.models import Project
from sig.models import SIG
from datetime import datetime
from sig.serializers import SIGSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response

@api_view(['GET'])
def detailsView(request,sig_name):
    sig_object = SIG.objects.get(name=sig_name)
    sig_data = SIGSerializer(sig_object).data
    return Response(sig_data)

backend-code/templates/sig/details.html
{% extends 'base.html' %}
{% load split %}
{% block content %}
{% load compress %}
{% compress css %}
{% load static %}
<style>
.proj-item:nth-child(odd) div.proj-info {
  float: right;
}
.proj-item:nth-child(odd) div.proj-image {
  float: left;
}
.proj-item:nth-child(even) div.proj-info {
  float: left;
}
.proj-item:nth-child(even) div.proj-image {
  float: right;
}
div {
    text-align: justify;
    text-justify: inter-word;
}
#lineheight {
    line-height: 130%;
}

</style>
{% endcompress %}
<div class="row">
    <div class="row center">
        <div class="col l12 s12">
            <h3><span>{{sig.name}}</span></h3>
        </div>
    </div>
    <div class="row center">
        <img src="/media/{{sig.avatar}}" class="responsive-img" width="350px">
    </div>
    <div class="row">
        <div class="col l10 offset-l1">
            <h5 style="line-height:1.5; text-align:justify;"> <span>{{sig.description}}</span></h5>
        </div>
    </div>
    
    
</div>
<div class="col l12 s12 center">
    <h4><span>See what our Core has to say about {{sig.name}}! </span></h4>
</div>
<div class="video-container center">
    
        <div class="video-container">
            <iframe width="80%" height="70%" src="{{sig.website_talk_url}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
</div>
        
<div class="row">
    <div class="col l10 offset-l1">
        <h4 class="center"><span>Projects {{year}}</span></h4>
    </div>
</div>
    {% for project in projects %}
<div class="row proj-item">
    <div class="col l10 offset-l1 s12 z-depth-3">
        <div class="col l4 s12 proj-image center">
            <img src={{project.img_url}} class="responsive-img" height="250px" width="250px" style="padding-top: 25px;">
        </div>
        <div class="col l8 s12 proj-info">
            <h4 class="center">{{project.name}}</h4>
            <div class="col l12 s12 center">
                <h6 class="center">{{project.summary}}</h6>
                <div class="row center">
                    <a class="waves-effect waves-light btn-small" href="{% url 'project:details' project.id %}">View Details</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}
<div class="row center">
    <a class="waves-effect waves-light btn" href="{% url 'project:index' sig %}"><i class="material-icons small" style="vertical-align: bottom;">list</i>More Projects</a>
</div>
{% endblock %}