backend-code/SMP/urls.py
from django.urls import path,include
from SMP import views

app_name = 'SMP'
urlpatterns = [
    path('', views.indexView, name='index'),
    path('<sig_name>/', views.detailsView, name='details'),
]

backend-code/account/urls.py
from django.urls import path, include
from account import views
from rest_framework.authtoken import views as rest_framework_views

app_name = 'account'
urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('edit/', views.editView, name='edit'),
    path('change_password/', views.changePasswordView, name='change_password'),
    path('get_auth_token/',views.CustomAuthToken.as_view(), name='get_auth_token')
]

backend-code/event/urls.py
from django.urls import path,include
from event import views

app_name = 'event'
urlpatterns = [
    path('', views.indexView, name='index'),
    path('add/', views.addView, name='add'),
    # path('edit/<event_id>', views.editView, name='edit'),
    #Make sure this is the last route always
    path('<event_name>/', views.detailsView, name='details'),
]

backend-code/project/urls.py
from django.urls import path,include
from project import views

app_name = 'project'
urlpatterns = [
    path('all/<sig_name>/', views.indexViewAll, name='indexAll'),
    path('current/<sig_name>/', views.indexViewCurrent, name='indexCurrent'),
    #Make sure this is the last route always
    path('<int:project_id>/', views.detailsView, name='details'),

]

backend-code/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# admin.autodiscover()
# admin.site.enable_nav_sidebar = False
# a

admin.site.site_header = "ISTE Website Admin Page"
admin.site.index_title = "Admin page"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account")),
    path("project/", include("project.urls", namespace="project")),
    path("event/", include("event.urls", namespace="event")),
    path("recs/", include("recruitment.urls", namespace="recruitment")),
    path("sig/", include("sig.urls", namespace="sig")),
    path("team/", include("team.urls", namespace="team")),
    path("smp/", include("SMP.urls", namespace="SMP")),
    path("ctf/", include("ctf.urls", namespace="CTF")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("squareoneleaderboard/",include("squareonelb.urls", namespace="squareonelb")),
    path('obscura/', include('obscura.urls', namespace='obscura')),
    path('cryptonite/', include('cryptonite.urls', namespace='cryptonite')),
    path('obsidian/', include('obsidian.urls', namespace="obsidian")),
    path('gallery/',include("gallery.urls",namespace="gallery")),
    path('clutchMysteryBox/',include("clutchMysteryBox.urls",namespace="clutchMysteryBox"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend-code/project/models.py
from django.db import models
from datetime import datetime
from ckeditor_uploader.fields import RichTextUploadingField

from website.helperFunctions import project_poster_upload_path, default_project_image_path
from account.models import User
from sig.models import SIG

def year_choices():
    return [(r,r) for r in range(2018, datetime.today().year +1)]

class Project(models.Model):
    name = models.CharField(
        default = "",
        max_length = 200
    )
    tags = models.CharField(
        default = "",
        max_length = 200
    )
    #Members of the project, 'editable_by' is used due 
    #to RBAC logic used in @check_ edit_access decorator
    editable_by = models.ManyToManyField(User)
    sigs = models.ManyToManyField(
        to=SIG)
    year = models.IntegerField(
        choices = year_choices(),
        default=datetime.today().year
    )
    summary = models.TextField(
        default="Project Summary",
        blank=False,
        editable=True
    )
    description = RichTextUploadingField()
    image = models.ImageField(
        default=default_project_image_path,
        upload_to=project_poster_upload_path,
        blank=True
    )

    def __str__(self):
        return self.name 

backend-code/project/views.py
from datetime import datetime
from rest_framework.decorators import api_view
from rest_framework.response import Response

from website.decorators import check_member_year, check_edit_access_project, login_required, check_core_member
from project.models import Project
from account.models import User
from sig.models import SIG
from project.serializers import ProjectSerializer


# def mapNewId(projects):
#     l = []
#     current_ids = {
#         18: 'catalyst1',
#         20: 'catalyst2',
#         103: 'catalyst3',

#         4: 'charge1',
#         31: 'charge2',
#         25: 'charge3',
#         26: 'charge4',
#         102: 'charge5',
#         28: 'charge6',

#         37: 'chronicle1',
#         84: 'chronicle2',
#         35: 'chronicle3',

#         34: 'clutch1',
#         29: 'clutch2',
#         22: 'clutch3',
#         2: 'clutch4',

#         100: 'concrete2',
#         15: 'concrete1',
#         5: 'concrete4',
#         32: 'concrete3',
#         8: 'concrete5',

#         17: 'create1',
#         35: 'create2',

#         21: 'credit5',
#         11: 'credit6',
#         3: 'credit3',
#         16: 'credit4',
#         9: 'credit2',
#         7: 'credit1',
#         27: 'credit7',

#         19: 'crypt2',
#         14: 'crypt5',
#         99: 'crypt1',
#         13: 'crypt4',
#         30: 'crypt3',
#         24: 'crypt6'

#     }
#     for project in projects:
#         if project['id'] in current_ids:
#             d = project
#             d['id'] = current_ids[project['id']]
#             l.append(d)
#     return l


@api_view(['GET'])
def indexViewAll(request, sig_name):
    projects = {}
    if sig_name == 'Catalyst':
        start_year = 2019
    else:
        start_year = 2018
    for year in range(start_year, datetime.today().year+1):
        projects_obj = Project.objects.filter(
            sigs__name=sig_name,
            year=year
        ).order_by('name')
        projects_data = ProjectSerializer(projects_obj, many=True).data
        projects[str(year)+'-'+str(year+1)[2:]] = projects_data
    return Response(projects)


@api_view(['GET'])
def indexViewCurrent(request, sig_name):
    this_year = datetime.now().year
    this_month = datetime.now().month
    if this_month < 7:
        this_year = this_year-1
    sig = SIG.objects.get(
        name=sig_name
    )
    projects_obj = Project.objects.filter(
        sigs__name=sig.name,
        year=this_year
    ).order_by('name')
    projects_data = ProjectSerializer(projects_obj, many=True).data

    # mapping for custom id, to be removed later
    # projects_data = mapNewId(projects_data)

    return Response(projects_data)


@api_view(['GET'])
def detailsView(request, project_id):
    try:
        project_obj = Project.objects.get(
            id=project_id
        )
    except:
        return Response({})
    project_data = ProjectSerializer(project_obj).data
    return Response(project_data)

backend-code/templates/project/add.html
{% extends 'base.html' %}

{% block content %}
<div class="row center">
    <div class="col l6 offset-l3 m8 offset-m2 s12">
        <div class="card">
            <div class="card-content black-text">
                <span class="center card-title">
                    Add Project
                </span> 
                <form method="POST" action="{% url 'project:add'%}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix">
                                dashboard
                            </i>
                            
                            {{form.name}}
                            <label>
                                Project {{form.name.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix">
                                event
                            </i>
                            {{form.tags}}
                            <label>
                                {{form.tags.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                people
                            </i>
                            {{form.editable_by}}
                            <label>
                                {{form.editable_by.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                polymer
                            </i>
                            {{form.sigs}}
                            <label>
                                {{form.sigs.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                access_time
                            </i>
                            {{form.year}}
                            <label>
                                {{form.year.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                add_photo_alternate
                            </i>
                            {{form.img_url}}
                            <label>
                               Insert Project Image URL
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="text-field col s10 valign-wrapper offset-s1">
                            <label>
                                {{form.summary.label}}
                            </label>
                            {{form.summary}}

                        </div>
                    </div>
                    <div class="row">
                        <div class="text-field col s10 valign-wrapper offset-s1">
                            <label>
                                {{form.description.label}}
                            </label>
                            {{form.description}}

                        </div>
                    </div>
                    
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Create project
                        <i class="material-icons right">
                            create
                        </i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

backend-code/templates/project/details.html
{% extends 'base.html' %}
{% load split %}
{% block content %}
<div class="row-center">
  <div class="col l6 offset -l3 s12">
    <div class="card-panel hoverable">
      {% if user.is_authenticated %}
      <a id="edit" href="{% url 'project:edit' project.id %}" class="btn btn-floating btn-large top-right" style="float:right;margin:0 0 0 auto;">
        <i class="material-icons">edit</i>
      </a>
      {% endif %}
      <div class="card-content black-text">
        <h3>{{ project.name}}</h3>
        <div class="center">
          <h5>
            {% for sig in project.sigs.all %}
              {% if forloop.first %}
                {{sig}} 
              {% else %}
                ,{{sig}}
              {% endif %}
            {% endfor %}
            
            | {{ project.year }}
          </h5> 
        </div>
        <div style="border-bottom:1px black solid" class="row">
        <i class="material-icons">person</i><span style="font-size:26px;">Members</span>
      </div>
      <div class="center row">
          <div class='flexrow'>
              {% for member in project.editable_by.all %}
              <a class="core_img z-depth-2">
                  <div class="img__overlay">
                      {{member.first_name}} {{member.last_name}}
                      <br>
                  </div>
                  <img src='{{member.avatar.url}}'>
              </a>
              {% endfor %}
          </div>
      </div>
        
      <div style="border-bottom:1px black solid" class="row">
        <i class="material-icons">description</i><span style="font-size:26px;">Description</span>
      </div>
          <div class="row ckeditor_content">
            {{ project.description|safe }}
          </div>
      <div style="border-bottom:1px black solid" class="row">
        <i class="material-icons">local_offer</i><span style="font-size:26px;">Tags</span>
      </div>
      {% for tag in project.tags|split:',' %}
        <div class="chip">
          {{tag}}
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

backend-code/templates/project/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="row center">
    <div class="col l6 offset-l3 m8 offset-m2 s12">
        <div class="card">
            <div class="card-content black-text">
                <span class="center card-title">
                    Edit Project
                </span> 
                <form method="POST" action="{% url 'project:edit' project.id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix">
                                dashboard
                            </i>
                            
                            {{form.name}}
                            <label>
                                {{form.name.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix">
                                event
                            </i>
                            {{form.tags}}
                            <label>
                                {{form.tags.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                people
                            </i>
                            {{form.editable_by}}
                            <label>
                                {{form.editable_by.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                polymer
                            </i>
                            {{form.sigs}}
                            <label>
                                {{form.sigs.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                access_time
                            </i>
                            {{form.year}}
                            <label>
                                {{form.year.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                add_photo_alternate
                            </i>
                            {{form.img_url}}
                            <label>
                               Insert Project Image URL
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="text-field col s10 valign-wrapper offset-s1">
                            <label>
                                {{form.summary.label}}
                            </label>
                            {{form.summary}}

                        </div>
                    </div>
                    <div class="row">
                        <div class="text-field col s10 valign-wrapper offset-s1">
                            <label>
                                {{form.description.label}}
                            </label>
                            {{form.description}}

                        </div>
                    </div>
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Edit project
                        <i class="material-icons right">
                            create
                        </i>
                    </button>
                </form>
{% endblock content %}

backend-code/templates/project/index.html
{% extends 'base.html' %}
{% block content %}
<h3><span>{{sig_name}} Projects</span></h3>     

{% for year, yearly_projects in projects.items %}
  <h5>{{ year }}</h5>
  <ul>
    {% for project in yearly_projects %}
      <a href="{% url 'project:details' project.id %}"><li>{{project.name}}</li></a>
    {% endfor %}
  </ul>
{% endfor %}
 
<h5>Check out ISTE's Virtual Project Expo 2019-20 <a href="https://sites.google.com/view/isteprojectexpo/" target="_blank">here!</a></h5>

{% endblock %}
{% block scripts %}
  {% load static %}
  {% load compress %}
  {% compress js %}
  <script type="text/javascript" src="{% static 'js/project/main.js'%}"></script>
  {% endcompress %}
{% endblock %}