backend-code/SMP/urls.py
from django.urls import path,include
from SMP import views

app_name = 'SMP'
urlpatterns = [
    path('', views.indexView, name='index'),
    path('<sig_name>/', views.detailsView, name='details'),
]

backend-code/account/urls.py
from django.urls import path, include
from account import views
from rest_framework.authtoken import views as rest_framework_views

app_name = 'account'
urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('edit/', views.editView, name='edit'),
    path('change_password/', views.changePasswordView, name='change_password'),
    path('get_auth_token/',views.CustomAuthToken.as_view(), name='get_auth_token')
]

backend-code/event/urls.py
from django.urls import path,include
from event import views

app_name = 'event'
urlpatterns = [
    path('', views.indexView, name='index'),
    path('add/', views.addView, name='add'),
    # path('edit/<event_id>', views.editView, name='edit'),
    #Make sure this is the last route always
    path('<event_name>/', views.detailsView, name='details'),
]

backend-code/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# admin.autodiscover()
# admin.site.enable_nav_sidebar = False
# a

admin.site.site_header = "ISTE Website Admin Page"
admin.site.index_title = "Admin page"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account")),
    path("project/", include("project.urls", namespace="project")),
    path("event/", include("event.urls", namespace="event")),
    path("recs/", include("recruitment.urls", namespace="recruitment")),
    path("sig/", include("sig.urls", namespace="sig")),
    path("team/", include("team.urls", namespace="team")),
    path("smp/", include("SMP.urls", namespace="SMP")),
    path("ctf/", include("ctf.urls", namespace="CTF")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("squareoneleaderboard/",include("squareonelb.urls", namespace="squareonelb")),
    path('obscura/', include('obscura.urls', namespace='obscura')),
    path('cryptonite/', include('cryptonite.urls', namespace='cryptonite')),
    path('obsidian/', include('obsidian.urls', namespace="obsidian")),
    path('gallery/',include("gallery.urls",namespace="gallery")),
    path('clutchMysteryBox/',include("clutchMysteryBox.urls",namespace="clutchMysteryBox"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend-code/event/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

from account.models import User
from sig.models import SIG
from website.settings import SIG_CHOICES
from website.helperFunctions import event_poster_upload_path, default_event_poster_path

class Event(models.Model):
    name = models.CharField(
        max_length=100,
        blank=False,
        editable=True
    )
    date_time = models.DateTimeField(
        auto_now=False
    )
    no_of_participants = models.IntegerField(
        default=3
    )
    # Points of contact
    contacts = models.ManyToManyField(
        to=User
    )
    #Used to provide edit access of an event object to others
    editable_by = models.ManyToManyField(
        to=User,
        related_name='editable_by'
    )
    poster = models.ImageField(
        default=default_event_poster_path,
        upload_to=event_poster_upload_path,
        blank=True
    )
    # poster = models.TextField(
    #     default=""
    # )
    sigs = models.ManyToManyField(
        to=SIG,
        related_name='sigs'
    )
    #Google form link for registration
    form_link = models.URLField(
        blank=True,
        max_length=200
    )
    #Whatsapp spam message, will be used as event details
    publicity_message = RichTextUploadingField(
        blank=True,
        editable=True
    )
    venue = models.CharField(
        default="MS Teams",
        max_length=100,
        blank=True,
        editable=True
    )

    def __str__(self):
        return self.name + 'id' + str(self.id)

backend-code/event/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Q
from datetime import datetime, timedelta
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
import cloudinary.uploader as up
import cloudinary

from website.permissions import IsCoreMember
from account.models import User
from sig.models import SIG
from event.models import Event
from event.serializers import EventSerializer
from website.decorators import check_core_member, check_member_year, check_edit_access_event, login_required


@api_view(['GET'])
def indexView(request):
    yesterday = datetime.today() - timedelta(days=1)

    events_obj = Event.objects.exclude(
        date_time__lte=yesterday
    ).order_by('date_time')
    events_data = EventSerializer(events_obj, many=True, fields=[
                                  'name', 'date_time', 'poster', 'sigs', 'venue']).data
    return Response(events_data)

# This API is not yet being used


@api_view(['POST'])
@permission_classes([IsAuthenticated, IsCoreMember])
def addView(request):
    data = request.POST
    event = Event(
        name=data['name'],
        date_time=data['date_time'],
        no_of_participants=data['no_of_participants'],
        poster=request.FILES['poster'],
        form_link=data['form_link'],
        publicity_message=data['publicity_message'],
        venue=data['venue'],
    )
    event.save()
    event.contacts.set(data['contacts'])
    event.editable_by.set(data['editable_by'])
    event.sigs.set(data['sigs'])
    event.save()
    return Response({'msg': 'Event added successfully'})

# Create more APIs to edit and delete Events, making it easier for core members to edit stuff


@api_view(['GET'])
def detailsView(request, event_name):
    event_obj = Event.objects.get(
        name=event_name
    )
    event_data = EventSerializer(event_obj).data
    return Response(event_data)

backend-code/templates/event/add.html
{% extends 'base.html' %}

{% block content %}
    <div class="row center">
        <div class="col l6 offset-l3 m8 offset-m2 s12">
            <div class="card">
                <div class="card-content black-text">
                    <span class="center card-title">
                        Add Event
                    </span> 
                    <form method="POST" action="{% url 'event:add'%}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s8">
                                <i class="form-icon material-icons prefix">
                                    event
                                </i>
                                {{form.name}}
                                <label>
                                    {{form.name.label}}
                                </label>
                            </div>
                            <div class="input-field col s4">
                                <i class="form-icon material-icons prefix">
                                    group
                                </i>
                                {{form.no_of_participants}}
                                <label>
                                    {{form.no_of_participants.label}}
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="form-icon material-icons prefix">
                                    date_range
                                </i>
                                {{form.date_time}}
                                <label>
                                    {{form.date_time.label}}
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="form-icon material-icons prefix" style="left:10px">
                                    person
                                </i>
                                {{form.contacts}}
                                <label>
                                    {{form.contacts.label}}
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="form-icon material-icons prefix" style="left:10px">
                                    person
                                </i>
                                {{form.editable_by}}
                                <label>
                                    {{form.editable_by.label}}
                                </label>
                            </div>
                        </div>


                        <div class="row">
                            <div class="input-field col s12">
                                <i class="form-icon material-icons prefix" style="left:10px">
                                    polymer
                                </i>
                                {{form.sigs}}
                                <label>
                                    {{form.sigs.label}}
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="form-icon material-icons prefix">
                                    link
                                </i>
                                {{form.form_link}}
                                <label>
                                    {{form.form_link.label}}
                                </label>
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                                <i class="form-icon material-icons prefix">
                                    location_on
                                </i>
                                {{form.venue}}
                                <label>
                                    {{form.venue.label}}
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="text-field col s10 valign-wrapper offset-s1">
                                <label>
                                    {{form.publicity_message.label}}
                                </label>
                                {{form.publicity_message}}
                                                                
                            </div>
                        </div>
                        <div class="row">
                            <div class="file-field input-field">
                                <div class="btn">
                                    <span>Poster</span>
                                    <input type="file" name="poster" accept="image/*" id="img">
                                </div>
                                <div class="file-path-wrapper">
                                    <input class="file-path validate" type="text">
                                </div>
                            </div>
                        </div>
                        <button class="btn waves-effect waves-light" type="submit" name="action">
                            Create event
                            <i class="material-icons right">
                                create
                            </i>
                        </button>    
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

backend-code/templates/event/details.html
{% extends 'base.html' %}
{% block content %}
<h3><span>{{event.name}}</span></h3>

<div class="row">
    <div class="col l16 m8 offset-m2 s12">
        <div class="card hoverable z-depth-3">
            <div class="card-image responsive-img">
                <img src="{{event.poster.url}}">
                {% if user.is_authenticated %}
                    <a id="edit" href="{% url 'event:edit' event.id %}" class="halfway-fab btn-floating">
                        <i class="material-icons">edit</i>
                    </a>
                {% endif %}
            </div>
            <div class="card-content">
                <p class="grey-text">
                    <i class="inline-icon material-icons">date_range</i> 
                    {{event.date_time | date:"d/m/Y P"}} 
                </p>
                <br>
                <p class="grey-text">
                    <i class="inline-icon material-icons">location_on</i>{{event.venue}}
                </p>
                <br>
                <p class="grey-text">
                    <i class="inline-icon material-icons">group</i>
                    {% for sig in event.sigs.all %}
                        {% if forloop.first %}
                            {{sig}}
                        {% else %}
                            , {{sig}}
                        {% endif %}
                    {% endfor %}
                </p>
                <br>   
                <p class="grey-text">
                    Maximum group members: {{event.no_of_participants}}
                </p>
                <br>

                <div class="divider"></div>
                <h5 class="center">About the event</h5>
                <br>
                <p class=" grey-text text-darken-2">
                    {{event.publicity_message | safe}}
                </p><br>
                
                <div class="divider"></div><br>
                <p class=" grey-text text-darken-2">
                    Points of contact:<br>
                    <ul>
                        {% for member in event.contacts.all %}
                            {% if member.gender == 'F' %}
                                <li>{{member.first_name}} {{member.last_name}} : {{member.hostel_address}}</li>
                            {% else %}
                                <li>{{member.first_name}} {{member.last_name}} : <a href="tel:{{member.phone_number }}">{{member.phone_number}}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </p><br>
            <div class="card-action">
                <center>
                    <a class="indigo-text" href="{{event.form_url}}">Register Now</a>
                </center>
            </div>

        </div>
    </div>
</div>

{% endblock %}

backend-code/templates/event/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="row center">

    <div class="col l6 offset-l3 m8 offset-m2 s12">

        <div class="card">
            <div class="card-content black-text">
                <span class="center card-title">
                    Edit Event
                </span> 
                <form method="POST" action="{% url 'event:edit' id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-image responsive-img">
                        <img src="{{poster}}">
                    </div>
                    <div class="row">
                        <div class="input-field col s8">
                            <i class="form-icon material-icons prefix">
                                event
                            </i>
                            {{form.name}}
                            <label>
                                {{form.name.label}}
                            </label>
                        </div>
                        <div class="input-field col s4">
                            <i class="form-icon material-icons prefix">
                                group
                            </i>
                            {{form.no_of_participants}}
                            <label>
                                {{form.no_of_participants.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix">
                                date_range
                            </i>
                            {{form.date_time}}
                            <label>
                                {{form.date_time.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                person
                            </i>
                            {{form.contacts}}
                            <label>
                                {{form.contacts.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                person
                            </i>
                            {{form.editable_by}}
                            <label>
                                {{form.editable_by.label}}
                            </label>
                        </div>
                    </div>


                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix" style="left:10px">
                                polymer
                            </i>
                            {{form.sigs}}
                            <label>
                                {{form.sigs.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix">
                                link
                            </i>
                            {{form.form_link}}
                            <label>
                                {{form.form_link.label}}
                            </label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                            <i class="form-icon material-icons prefix">
                                location_on
                            </i>
                            {{form.venue}}
                            <label>
                                {{form.venue.label}}
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="text-field col s10 valign-wrapper offset-s1">
                            <label>
                                {{form.publicity_message.label}}
                            </label>
                            {{form.publicity_message}}

                        </div>
                    </div>
                    <div class="row">
                        <div class="file-field input-field">
                            <div class="btn">
                                <span>Poster</span>
                                <input type="file" name="poster" accept="image/*" id="img">
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text">
                            </div>
                        </div>
                    </div>                
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Save Changes
                        <i class="material-icons right">
                            create
                        </i>
                    </button>   
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

backend-code/templates/event/index.html
{% extends 'base.html' %}
{% block content %}
{% if isEmpty %}
<h3><span>No Events scheduled for now</span></h3>
{% else %}

<h3><span>Upcoming Events</span></h3>

<div class="row">
    {% for event in events %}
    <div class="col s12 m6 l4">
        <div class="card hoverable large z-depth-3">
                <div class="card-image">
                    <img src="{{event.poster.url}}">
                </div>
                <div class="card-content">
                    <h5 class="center">{{event.name}}</h5>
                    <p class="grey-text">
                        <i class="inline-icon material-icons">date_range</i> 
                        {{event.date_time | date:"d/m/Y P"}} 
                    </p>
                    <br>
                    <p class="grey-text">
                        <i class="inline-icon material-icons">location_on</i>{{event.venue}}
                    </p>
                    <br>
                    <p class="grey-text">
                        <i class="inline-icon material-icons">polymer</i>
                        {% for sig in event.sigs.all %}
                            {% if forloop.first %}
                                {{sig}}
                            {% else %}
                                , {{sig}}
                            {% endif %}
                        {% endfor %}
                    </p>
                </div>

                <div class="card-action">
                    <center><a class="indigo-text" href="{% url 'event:details' event.name %}">View Details</a></center>
                </div>
 
            </div>
        </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}